### ISSUE TITLE
When exporting pdf, the title is displayed incorrectly

### ISSUE THREAD

**Issue by aetherrootr** [etigerstudio/typora-misty-theme#16]
![image](https://user-images.githubusercontent.com/20625707/92952268-45b34300-f492-11ea-8dd6-ad9571611dd5.png)

I tried many files to export pdf, and this error occurred, and I tried to export html file, but no such error occurred

**Comment by etigerstudio** [comment]
抱歉，回复晚了。

我注意到 Typora 的新版（0.9.9.35.2）更新说明有提到修复第三方主题导出PDF时出现的相关问题，可以尝试升级Typora 到最新 beta 版再确认一下问题是否得到修复。

如果问题依旧存在，欢迎继续回帖，并附上你所使用的版本号等有助定位问题的信息。

----

Sorry for my late reply. 

I found that "Fix issues with PDF export on 3rd party themes."  is mentioned in release notes of Typora Beta 0.9.9.35.2. You may update your Typora to see whether this issue is addressed in the latest update.

If this issue continues to occur, feel free to repost here. The version number you're using and other related information could be helpful to identify the issue.

----

<img width="504" alt="Screen Shot 2020-09-27 at 1 31 09 AM" src="https://user-images.githubusercontent.com/2973222/94346824-df1d5000-0061-11eb-8ce6-331d42a9aba4.png">

**Comment by etigerstudio** [comment]
I'm closing this issue. If any problem persists,  you're welcome to comment here or open a new issue.

**Comment by Yuanda-Dong** [comment]
I have the same issue when exporting pdfs, the version is typora 0.9.95-1, on manjaro linux.

**Comment by etigerstudio** [comment]
> I have the same issue when exporting pdfs, the version is typora 0.9.95-1, on manjaro linux.

Hi there! I've tested pdf exporting on `Ubuntu 20.04 LTS`, Typora `0.9.96 beta`(I cannot install manjaro at the moment):

![Screen Shot 2020-10-20 at 9 33 47 PM](https://user-images.githubusercontent.com/2973222/96595816-a6019400-131e-11eb-86e8-f198fbd94af2.png)

What it renders in application window(Misty Light Windows):

![Screen Shot 2020-10-20 at 9 33 53 PM](https://user-images.githubusercontent.com/2973222/96595804-a39f3a00-131e-11eb-9363-87ead812fef8.png)

What the exported pdf look like(no noticeable misrendering could be seen):

![Screen Shot 2020-10-20 at 9 34 29 PM](https://user-images.githubusercontent.com/2973222/96595813-a4d06700-131e-11eb-94cc-0005c0203357.png)

As I failed to reproduce this issue on Ubuntu and have no concrete idea about what's going on, I recommend that you update Typora to latest version available and upload some screenshots(such as Typora main editing window, exported pdf & html in Misty theme & default built-in Github theme respectively). 

I hope you could provide some detailed information so that I may spot where the problem lies.

**Comment by Yuanda-Dong** [comment]
Hi, 
Upgrading to 0.9.96 beta solves the problem. It's only released yesterday on AUR.

**Comment by aetherrootr** [comment]
或者您可以回滚过去的版本，我回滚到了
![image](https://user-images.githubusercontent.com/20625707/96702238-26c69b80-13c4-11eb-98ef-bbf0032f961f.png)
解决了所有的问题
