### ISSUE TITLE
I think the emphasis is not displayed correctly (in Windows).

### ISSUE THREAD

**Issue by GoodWillChase** [etigerstudio/typora-misty-theme#4]
I think it should be:

```
strong, b {
    font-weight: 800;
}
```

**Comment by etigerstudio** [comment]
Hello, Thank you for try Misty Theme out!

I've made some tests before and finally selected 400 as body font weight, 500 as strong/b font weight on Windows(300, 400 on macOS respectively).
For me, it turns out that 500 & 600 render as same thickness(see first shot) and 700 & 800 render as same thickness(see second shot):

![500](https://user-images.githubusercontent.com/2973222/54494607-1d876a00-4917-11e9-99b0-5a88f92bd936.png)
![800](https://user-images.githubusercontent.com/2973222/54494608-1eb89700-4917-11e9-8a68-23dc63c560c1.png)

As you can see in these 2 shots, whose font rendered is 'Segoe UI', 500 & 600 are a little thin and visually subtle, while 700 & 800 are rather thick and visually obstructive, damaging entire feel.

For this reason, I choose 500(may also be adjusted to 600 if needed) instead of 800 as strong/b font weight on Windows.

**Comment by etigerstudio** [comment]
I'm planning to change font weight to (300,500) on macOS & (400,600) on Windows from (300,400) on macOS & (400,500) on Windows to make it a little more obvious to distinguish between normal & bold text.

**Comment by GoodWillChase** [comment]
I've done some tests and maybe I know where the problem is.

I changed strong/b font weight (line 505 in the 'misty-light-windows.css').

For me, it turns out that 400 & 500 render as same thickness(see first shot) and 600 & 700 render as same thickness(see second shot) and 800 & 900 render as same thickness which is much more thicker(see third shot):

![FSCapture_2019-03-18_10-52-13](https://user-images.githubusercontent.com/26741114/54504458-b4cbdc00-496e-11e9-931d-5e1afc6aef40.png)

![FSCapture_2019-03-18_11-05-11](https://user-images.githubusercontent.com/26741114/54504471-c319f800-496e-11e9-8b9c-24b8ce71ffbe.png)

![FSCapture_2019-03-18_11-08-06](https://user-images.githubusercontent.com/26741114/54504477-ca410600-496e-11e9-8132-dd33eaa1027b.png)


**So I think you just need to choose 600 instead of 500 as strong/b font weight on Windows and it will be all okay.**

Maybe it's a Windows System problem or something else. I don't know. Hope it helps.

**Comment by etigerstudio** [comment]
Thank you for opening this issue & doing experiments!

Fixed in [v0.4.1](https://github.com/etigerstudio/typora-misty-theme/releases/v0.4.1).
If you find any other problem or have any other idea on the theme, free feel to open up another issue!
